package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:301</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class alert extends Structure {
	public int timestamp;
	/// C type : char*
	public Pointer message;
	/// C type : char*
	public Pointer what;
	public int category;
	public alert() {
		super();
	}
    @Override
    protected List getFieldOrder() {
		return Arrays.asList(new String[]{"timestamp", "message", "what", "category"});
	}
	/**
	 * @param message C type : char*<br>
	 * @param what C type : char*
	 */
	public alert(int timestamp, Pointer message, Pointer what, int category) {
		super();
		this.timestamp = timestamp;
		this.message = message;
		this.what = what;
		this.category = category;
	}
	public static class ByReference extends alert implements Structure.ByReference {
		
	};
	public static class ByValue extends alert implements Structure.ByValue {
		
	}
}
