package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:540</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class dht_get_peers_alert extends Structure {
	/// C type : alert
	public alert alert;
	/// C type : const char*
	public Pointer info_hash;
	public dht_get_peers_alert() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"alert", "info_hash"});
	}
	/**
	 * @param alert C type : alert<br>
	 * @param info_hash C type : const char*
	 */
	public dht_get_peers_alert(alert alert, Pointer info_hash) {
		super();
		this.alert = alert;
		this.info_hash = info_hash;
	}
	public static class ByReference extends dht_get_peers_alert implements Structure.ByReference {
		
	};
	public static class ByValue extends dht_get_peers_alert implements Structure.ByValue {
		
	};
}
