package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:290</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class endpoint extends Structure {
	/// C type : const char*
	public Pointer addr;
	public int port;
	/// C type : error_code
	public error_code error;
	public endpoint() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"addr", "port", "error"});
	}
	/**
	 * @param addr C type : const char*<br>
	 * @param error C type : error_code
	 */
	public endpoint(Pointer addr, int port, error_code error) {
		super();
		this.addr = addr;
		this.port = port;
		this.error = error;
	}
	public static class ByReference extends endpoint implements Structure.ByReference {
		
	};
	public static class ByValue extends endpoint implements Structure.ByValue {
		
	};
}
