package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:580</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class file_entry extends Structure {
	/// C type : const char*
	public Pointer path;
	public long size;
	public long mtime;
	public byte pad_file;
	public byte hidden_attribute;
	public byte executable_attribute;
	public byte symlink_attribute;
	/// C type : const char*
	public Pointer symlink_path;
	public file_entry() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"path", "size", "mtime", "pad_file", "hidden_attribute", "executable_attribute", "symlink_attribute", "symlink_path"});
	}
	/**
	 * @param path C type : const char*<br>
	 * @param symlink_path C type : const char*
	 */
	public file_entry(Pointer path, long size, long mtime, byte pad_file, byte hidden_attribute, byte executable_attribute, byte symlink_attribute, Pointer symlink_path) {
		super();
		this.path = path;
		this.size = size;
		this.mtime = mtime;
		this.pad_file = pad_file;
		this.hidden_attribute = hidden_attribute;
		this.executable_attribute = executable_attribute;
		this.symlink_attribute = symlink_attribute;
		this.symlink_path = symlink_path;
	}
	public static class ByReference extends file_entry implements Structure.ByReference {
		
	};
	public static class ByValue extends file_entry implements Structure.ByValue {
		
	};
}
