package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:324</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class listen_failed_alert extends Structure {
	/// C type : alert
	public alert alert;
	/// C type : endpoint
	public endpoint endpoint;
	/// C type : error_code
	public error_code error;
	public listen_failed_alert() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"alert", "endpoint", "error"});
	}
	/**
	 * @param alert C type : alert<br>
	 * @param endpoint C type : endpoint<br>
	 * @param error C type : error_code
	 */
	public listen_failed_alert(alert alert, endpoint endpoint, error_code error) {
		super();
		this.alert = alert;
		this.endpoint = endpoint;
		this.error = error;
	}
	public static class ByReference extends listen_failed_alert implements Structure.ByReference {
		
	};
	public static class ByValue extends listen_failed_alert implements Structure.ByValue {
		
	};
}
