package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:477</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class performance_alert extends Structure {
	/// C type : torrent_alert
	public torrent_alert torrent_alert;
	/**
	 * <i>native declaration : c/libtorrent.h:473</i><br>
	 * enum values
	 */
	/**
	 * <i>native declaration : c/libtorrent.h:473</i><br>
	 * enum values
	 */
	public static interface performance_warning_t {
		/// <i>native declaration : c/libtorrent.h:468</i>
		public static final int outstanding_disk_buffer_limit_reached = (int)0;
		/// <i>native declaration : c/libtorrent.h:469</i>
		public static final int outstanding_request_limit_reached = (int)1;
		/// <i>native declaration : c/libtorrent.h:470</i>
		public static final int upload_limit_too_low = (int)2;
		/// <i>native declaration : c/libtorrent.h:471</i>
		public static final int download_limit_too_low = (int)3;
		/// <i>native declaration : c/libtorrent.h:472</i>
		public static final int send_buffer_watermark_too_low = (int)4;
	};
	/**
	 * @see performance_warning_t<br>
	 * C type : performance_warning_t
	 */
	public int warning_code;
	public performance_alert() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"torrent_alert", "warning_code"});
	}
	/**
	 * @param torrent_alert C type : torrent_alert<br>
	 * @param warning_code @see performance_warning_t<br>
	 * C type : performance_warning_t
	 */
	public performance_alert(torrent_alert torrent_alert, int warning_code) {
		super();
		this.torrent_alert = torrent_alert;
		this.warning_code = warning_code;
	}
	public static class ByReference extends performance_alert implements Structure.ByReference {
		
	};
	public static class ByValue extends performance_alert implements Structure.ByValue {
		
	};
}
