package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:345</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class portmap_log_alert extends Structure {
	/// C type : alert
	public alert alert;
	public int type;
	/// C type : const char*
	public Pointer msg;
	public portmap_log_alert() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"alert", "type", "msg"});
	}
	/**
	 * @param alert C type : alert<br>
	 * @param msg C type : const char*
	 */
	public portmap_log_alert(alert alert, int type, Pointer msg) {
		super();
		this.alert = alert;
		this.type = type;
		this.msg = msg;
	}
	public static class ByReference extends portmap_log_alert implements Structure.ByReference {
		
	};
	public static class ByValue extends portmap_log_alert implements Structure.ByValue {
		
	};
}
