package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:334</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class portmap_error_alert extends Structure {
	/// C type : alert
	public alert alert;
	public int mapping;
	public int type;
	/// C type : error_code
	public error_code error;
	public portmap_error_alert() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"alert", "mapping", "type", "error"});
	}
	/**
	 * @param alert C type : alert<br>
	 * @param error C type : error_code
	 */
	public portmap_error_alert(alert alert, int mapping, int type, error_code error) {
		super();
		this.alert = alert;
		this.mapping = mapping;
		this.type = type;
		this.error = error;
	}
	public static class ByReference extends portmap_error_alert implements Structure.ByReference {
		
	};
	public static class ByValue extends portmap_error_alert implements Structure.ByValue {
		
	};
}
