package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:507</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class save_resume_data_alert extends Structure {
	/// C type : torrent_alert
	public torrent_alert torrent_alert;
	/// C type : char*
	public Pointer resume_data;
	public int resume_data_size;
	public save_resume_data_alert() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"torrent_alert", "resume_data", "resume_data_size"});
	}
	/**
	 * @param torrent_alert C type : torrent_alert<br>
	 * @param resume_data C type : char*
	 */
	public save_resume_data_alert(torrent_alert torrent_alert, Pointer resume_data, int resume_data_size) {
		super();
		this.torrent_alert = torrent_alert;
		this.resume_data = resume_data;
		this.resume_data_size = resume_data_size;
	}
	public static class ByReference extends save_resume_data_alert implements Structure.ByReference {
		
	};
	public static class ByValue extends save_resume_data_alert implements Structure.ByValue {
		
	};
}
