package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:390</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class scrape_failed_alert extends Structure {
	/// C type : tracker_alert
	public tracker_alert tracker_alert;
	/// C type : const char*
	public Pointer msg;
	public scrape_failed_alert() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"tracker_alert", "msg"});
	}
	/**
	 * @param tracker_alert C type : tracker_alert<br>
	 * @param msg C type : const char*
	 */
	public scrape_failed_alert(tracker_alert tracker_alert, Pointer msg) {
		super();
		this.tracker_alert = tracker_alert;
		this.msg = msg;
	}
	public static class ByReference extends scrape_failed_alert implements Structure.ByReference {
		
	};
	public static class ByValue extends scrape_failed_alert implements Structure.ByValue {
		
	};
}
