package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:305</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class torrent_alert extends Structure {
	/// C type : alert
	public alert alert;
	/// C type : void*
	public Pointer handle;
	public torrent_alert() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"alert", "handle"});
	}
	/**
	 * @param alert C type : alert<br>
	 * @param handle C type : void*
	 */
	public torrent_alert(alert alert, Pointer handle) {
		super();
		this.alert = alert;
		this.handle = handle;
	}
	public static class ByReference extends torrent_alert implements Structure.ByReference {
		
	};
	public static class ByValue extends torrent_alert implements Structure.ByValue {
		
	};
}
