package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:586</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class torrent_title extends Structure {
	/// C type : const char*
	public Pointer name;
	/// C type : const char*
	public Pointer comment;
	/// C type : const char*
	public Pointer creator;
	public long mtime;
	public torrent_title() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"name", "comment", "creator", "mtime"});
	}
	/**
	 * @param name C type : const char*<br>
	 * @param comment C type : const char*<br>
	 * @param creator C type : const char*
	 */
	public torrent_title(Pointer name, Pointer comment, Pointer creator, long mtime) {
		super();
		this.name = name;
		this.comment = comment;
		this.creator = creator;
		this.mtime = mtime;
	}
	public static class ByReference extends torrent_title implements Structure.ByReference {
		
	};
	public static class ByValue extends torrent_title implements Structure.ByValue {
		
	};
}
