package com.github.axet.torrent.rasterbar;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.IntByReference;
import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>torrent</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface TorrentLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "torrent";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(TorrentLibrary.JNA_LIBRARY_NAME);
	public static final TorrentLibrary INSTANCE = (TorrentLibrary)Native.loadLibrary(TorrentLibrary.JNA_LIBRARY_NAME, TorrentLibrary.class);
	/**
	 * <i>native declaration : c/libtorrent.h:88</i><br>
	 * enum values
	 */
	/**
	 * <i>native declaration : c/libtorrent.h:88</i><br>
	 * enum values
	 */
	public static interface tags {
		/// <i>native declaration : c/libtorrent.h:1</i>
		public static final int TAG_END = (int)0;
		/**
		 * char const*, 2 character string<br>
		 * <i>native declaration : c/libtorrent.h:3</i>
		 */
		public static final int SES_FINGERPRINT = (int)1;
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:5</i>
		 */
		public static final int SES_LISTENPORT = (int)2;
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:7</i>
		 */
		public static final int SES_LISTENPORT_END = (int)3;
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:9</i>
		 */
		public static final int SES_VERSION_MAJOR = (int)4;
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:11</i>
		 */
		public static final int SES_VERSION_MINOR = (int)5;
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:13</i>
		 */
		public static final int SES_VERSION_TINY = (int)6;
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:15</i>
		 */
		public static final int SES_VERSION_TAG = (int)7;
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:17</i>
		 */
		public static final int SES_FLAGS = (int)8;
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:19</i>
		 */
		public static final int SES_ALERT_MASK = (int)9;
		/**
		 * char const*<br>
		 * <i>native declaration : c/libtorrent.h:21</i>
		 */
		public static final int SES_LISTEN_INTERFACE = (int)10;
		/**
		 * identifying the torrent to add<br>
		 * identifying the torrent to add<br>
		 * char const*<br>
		 * <i>native declaration : c/libtorrent.h:24</i>
		 */
		public static final int TOR_FILENAME = (int)256;
		/**
		 * char const*, specify size of buffer with TOR_TORRENT_SIZE<br>
		 * <i>native declaration : c/libtorrent.h:26</i>
		 */
		public static final int TOR_TORRENT = (int)(256 + 1);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:28</i>
		 */
		public static final int TOR_TORRENT_SIZE = (int)(256 + 2);
		/**
		 * char const*, must point to a 20 byte array<br>
		 * <i>native declaration : c/libtorrent.h:30</i>
		 */
		public static final int TOR_INFOHASH = (int)(256 + 3);
		/**
		 * char const*, must point to a 40 byte string<br>
		 * <i>native declaration : c/libtorrent.h:32</i>
		 */
		public static final int TOR_INFOHASH_HEX = (int)(256 + 4);
		/**
		 * char const*, url<br>
		 * <i>native declaration : c/libtorrent.h:34</i>
		 */
		public static final int TOR_MAGNETLINK = (int)(256 + 5);
		/**
		 * char const*<br>
		 * <i>native declaration : c/libtorrent.h:36</i>
		 */
		public static final int TOR_TRACKER_URL = (int)(256 + 6);
		/**
		 * char const*<br>
		 * <i>native declaration : c/libtorrent.h:38</i>
		 */
		public static final int TOR_RESUME_DATA = (int)(256 + 7);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:40</i>
		 */
		public static final int TOR_RESUME_DATA_SIZE = (int)(256 + 8);
		/**
		 * char const*<br>
		 * <i>native declaration : c/libtorrent.h:42</i>
		 */
		public static final int TOR_SAVE_PATH = (int)(256 + 9);
		/**
		 * char const*<br>
		 * <i>native declaration : c/libtorrent.h:44</i>
		 */
		public static final int TOR_NAME = (int)(256 + 10);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:46</i>
		 */
		public static final int TOR_PAUSED = (int)(256 + 11);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:48</i>
		 */
		public static final int TOR_AUTO_MANAGED = (int)(256 + 12);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:50</i>
		 */
		public static final int TOR_DUPLICATE_IS_ERROR = (int)(256 + 13);
		/**
		 * void*<br>
		 * <i>native declaration : c/libtorrent.h:52</i>
		 */
		public static final int TOR_USER_DATA = (int)(256 + 14);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:54</i>
		 */
		public static final int TOR_SEED_MODE = (int)(256 + 15);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:56</i>
		 */
		public static final int TOR_OVERRIDE_RESUME_DATA = (int)(256 + 16);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:58</i>
		 */
		public static final int TOR_STORAGE_MODE = (int)(256 + 17);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:60</i>
		 */
		public static final int SET_UPLOAD_RATE_LIMIT = (int)512;
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:62</i>
		 */
		public static final int SET_DOWNLOAD_RATE_LIMIT = (int)(512 + 1);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:64</i>
		 */
		public static final int SET_LOCAL_UPLOAD_RATE_LIMIT = (int)(512 + 2);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:66</i>
		 */
		public static final int SET_LOCAL_DOWNLOAD_RATE_LIMIT = (int)(512 + 3);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:68</i>
		 */
		public static final int SET_MAX_UPLOAD_SLOTS = (int)(512 + 4);
		/**
		 * int<br>
		 * <i>native declaration : c/libtorrent.h:70</i>
		 */
		public static final int SET_MAX_CONNECTIONS = (int)(512 + 5);
		/**
		 * int, torrent only<br>
		 * <i>native declaration : c/libtorrent.h:72</i>
		 */
		public static final int SET_SEQUENTIAL_DOWNLOAD = (int)(512 + 6);
		/**
		 * int, torrent only<br>
		 * <i>native declaration : c/libtorrent.h:74</i>
		 */
		public static final int SET_SUPER_SEEDING = (int)(512 + 7);
		/**
		 * int, session only<br>
		 * <i>native declaration : c/libtorrent.h:76</i>
		 */
		public static final int SET_HALF_OPEN_LIMIT = (int)(512 + 8);
		/**
		 * proxy_setting const*, session_only<br>
		 * <i>native declaration : c/libtorrent.h:78</i>
		 */
		public static final int SET_PEER_PROXY = (int)(512 + 9);
		/**
		 * proxy_setting const*, session_only<br>
		 * <i>native declaration : c/libtorrent.h:80</i>
		 */
		public static final int SET_WEB_SEED_PROXY = (int)(512 + 10);
		/**
		 * proxy_setting const*, session_only<br>
		 * <i>native declaration : c/libtorrent.h:82</i>
		 */
		public static final int SET_TRACKER_PROXY = (int)(512 + 11);
		/**
		 * proxy_setting const*, session_only<br>
		 * <i>native declaration : c/libtorrent.h:84</i>
		 */
		public static final int SET_DHT_PROXY = (int)(512 + 12);
		/**
		 * proxy_setting const*, session_only<br>
		 * <i>native declaration : c/libtorrent.h:86</i>
		 */
		public static final int SET_PROXY = (int)(512 + 13);
		/// <i>native declaration : c/libtorrent.h:87</i>
		public static final int SET_ALERT_MASK = (int)(512 + 14);
	};
	/**
	 * <i>native declaration : c/libtorrent.h:109</i><br>
	 * enum values
	 */
	/**
	 * <i>native declaration : c/libtorrent.h:109</i><br>
	 * enum values
	 */
	public static interface category_t {
		/// <i>native declaration : c/libtorrent.h:97</i>
		public static final int cat_error = (int)1;
		/// <i>native declaration : c/libtorrent.h:98</i>
		public static final int cat_peer = (int)2;
		/// <i>native declaration : c/libtorrent.h:99</i>
		public static final int cat_port_mapping = (int)4;
		/// <i>native declaration : c/libtorrent.h:100</i>
		public static final int cat_storage = (int)8;
		/// <i>native declaration : c/libtorrent.h:101</i>
		public static final int cat_tracker = (int)16;
		/// <i>native declaration : c/libtorrent.h:102</i>
		public static final int cat_debug = (int)32;
		/// <i>native declaration : c/libtorrent.h:103</i>
		public static final int cat_status = (int)64;
		/// <i>native declaration : c/libtorrent.h:104</i>
		public static final int cat_progress = (int)128;
		/// <i>native declaration : c/libtorrent.h:105</i>
		public static final int cat_ip_block = (int)256;
		/// <i>native declaration : c/libtorrent.h:106</i>
		public static final int cat_performance_warning = (int)512;
		/// <i>native declaration : c/libtorrent.h:107</i>
		public static final int cat_dht = (int)1024;
		/// <i>native declaration : c/libtorrent.h:108</i>
		public static final int cat_all_categories = (int)-1;
	};
	/**
	 * <i>native declaration : c/libtorrent.h:117</i><br>
	 * enum values
	 */
	/**
	 * <i>native declaration : c/libtorrent.h:117</i><br>
	 * enum values
	 */
	public static interface proxy_type_t {
		/// <i>native declaration : c/libtorrent.h:111</i>
		public static final int proxy_none = (int)0;
		/// <i>native declaration : c/libtorrent.h:112</i>
		public static final int proxy_socks4 = (int)1;
		/// <i>native declaration : c/libtorrent.h:113</i>
		public static final int proxy_socks5 = (int)2;
		/// <i>native declaration : c/libtorrent.h:114</i>
		public static final int proxy_socks5_pw = (int)3;
		/// <i>native declaration : c/libtorrent.h:115</i>
		public static final int proxy_http = (int)4;
		/// <i>native declaration : c/libtorrent.h:116</i>
		public static final int proxy_http_pw = (int)5;
	};
	/**
	 * <i>native declaration : c/libtorrent.h:122</i><br>
	 * enum values
	 */
	/**
	 * <i>native declaration : c/libtorrent.h:122</i><br>
	 * enum values
	 */
	public static interface storage_mode_t {
		/// <i>native declaration : c/libtorrent.h:119</i>
		public static final int storage_mode_allocate = (int)0;
		/// <i>native declaration : c/libtorrent.h:120</i>
		public static final int storage_mode_sparse = (int)1;
		/// <i>native declaration : c/libtorrent.h:121</i>
		public static final int storage_mode_compact = (int)2;
	};
	/**
	 * <i>native declaration : c/libtorrent.h:132</i><br>
	 * enum values
	 */
	/**
	 * <i>native declaration : c/libtorrent.h:132</i><br>
	 * enum values
	 */
	public static interface state_t {
		/// <i>native declaration : c/libtorrent.h:124</i>
		public static final int queued_for_checking = (int)0;
		/// <i>native declaration : c/libtorrent.h:125</i>
		public static final int checking_files = (int)1;
		/// <i>native declaration : c/libtorrent.h:126</i>
		public static final int downloading_metadata = (int)2;
		/// <i>native declaration : c/libtorrent.h:127</i>
		public static final int downloading = (int)3;
		/// <i>native declaration : c/libtorrent.h:128</i>
		public static final int finished = (int)4;
		/// <i>native declaration : c/libtorrent.h:129</i>
		public static final int seeding = (int)5;
		/// <i>native declaration : c/libtorrent.h:130</i>
		public static final int allocating = (int)6;
		/// <i>native declaration : c/libtorrent.h:131</i>
		public static final int checking_resume_data = (int)7;
	};
	/**
	 * <i>native declaration : c/libtorrent.h:280</i><br>
	 * enum values
	 */
	/**
	 * <i>native declaration : c/libtorrent.h:280</i><br>
	 * enum values
	 */
	public static interface alert_type {
		/// <i>native declaration : c/libtorrent.h:222</i>
		public static final int at_torrent_alert = (int)0;
		/// <i>native declaration : c/libtorrent.h:223</i>
		public static final int at_peer_alert = (int)1;
		/// <i>native declaration : c/libtorrent.h:224</i>
		public static final int at_tracker_alert = (int)2;
		/// <i>native declaration : c/libtorrent.h:225</i>
		public static final int at_read_piece_alert = (int)3;
		/// <i>native declaration : c/libtorrent.h:226</i>
		public static final int at_file_completed_alert = (int)4;
		/// <i>native declaration : c/libtorrent.h:227</i>
		public static final int at_file_renamed_alert = (int)5;
		/// <i>native declaration : c/libtorrent.h:228</i>
		public static final int at_file_rename_failed_alert = (int)6;
		/// <i>native declaration : c/libtorrent.h:229</i>
		public static final int at_performance_alert = (int)7;
		/// <i>native declaration : c/libtorrent.h:230</i>
		public static final int at_state_changed_alert = (int)8;
		/// <i>native declaration : c/libtorrent.h:231</i>
		public static final int at_tracker_error_alert = (int)9;
		/// <i>native declaration : c/libtorrent.h:232</i>
		public static final int at_tracker_warning_alert = (int)10;
		/// <i>native declaration : c/libtorrent.h:233</i>
		public static final int at_scrape_reply_alert = (int)11;
		/// <i>native declaration : c/libtorrent.h:234</i>
		public static final int at_scrape_failed_alert = (int)12;
		/// <i>native declaration : c/libtorrent.h:235</i>
		public static final int at_tracker_reply_alert = (int)13;
		/// <i>native declaration : c/libtorrent.h:236</i>
		public static final int at_dht_reply_alert = (int)14;
		/// <i>native declaration : c/libtorrent.h:237</i>
		public static final int at_tracker_announce_alert = (int)15;
		/// <i>native declaration : c/libtorrent.h:238</i>
		public static final int at_hash_failed_alert = (int)16;
		/// <i>native declaration : c/libtorrent.h:239</i>
		public static final int at_peer_ban_alert = (int)17;
		/// <i>native declaration : c/libtorrent.h:240</i>
		public static final int at_peer_unsnubbed_alert = (int)18;
		/// <i>native declaration : c/libtorrent.h:241</i>
		public static final int at_peer_snubbed_alert = (int)19;
		/// <i>native declaration : c/libtorrent.h:242</i>
		public static final int at_peer_error_alert = (int)20;
		/// <i>native declaration : c/libtorrent.h:243</i>
		public static final int at_peer_connect_alert = (int)21;
		/// <i>native declaration : c/libtorrent.h:244</i>
		public static final int at_peer_disconnected_alert = (int)22;
		/// <i>native declaration : c/libtorrent.h:245</i>
		public static final int at_invalid_request_alert = (int)23;
		/// <i>native declaration : c/libtorrent.h:246</i>
		public static final int at_torrent_finished_alert = (int)24;
		/// <i>native declaration : c/libtorrent.h:247</i>
		public static final int at_piece_finished_alert = (int)25;
		/// <i>native declaration : c/libtorrent.h:248</i>
		public static final int at_request_dropped_alert = (int)26;
		/// <i>native declaration : c/libtorrent.h:249</i>
		public static final int at_block_timeout_alert = (int)27;
		/// <i>native declaration : c/libtorrent.h:250</i>
		public static final int at_block_finished_alert = (int)28;
		/// <i>native declaration : c/libtorrent.h:251</i>
		public static final int at_block_downloading_alert = (int)29;
		/// <i>native declaration : c/libtorrent.h:252</i>
		public static final int at_unwanted_block_alert = (int)30;
		/// <i>native declaration : c/libtorrent.h:253</i>
		public static final int at_storage_moved_alert = (int)31;
		/// <i>native declaration : c/libtorrent.h:254</i>
		public static final int at_storage_moved_failed_alert = (int)32;
		/// <i>native declaration : c/libtorrent.h:255</i>
		public static final int at_torrent_deleted_alert = (int)33;
		/// <i>native declaration : c/libtorrent.h:256</i>
		public static final int at_torrent_delete_failed_alert = (int)34;
		/// <i>native declaration : c/libtorrent.h:257</i>
		public static final int at_save_resume_data_alert = (int)35;
		/// <i>native declaration : c/libtorrent.h:258</i>
		public static final int at_save_resume_data_failed_alert = (int)36;
		/// <i>native declaration : c/libtorrent.h:259</i>
		public static final int at_torrent_paused_alert = (int)37;
		/// <i>native declaration : c/libtorrent.h:260</i>
		public static final int at_torrent_resumed_alert = (int)38;
		/// <i>native declaration : c/libtorrent.h:261</i>
		public static final int at_torrent_checked_alert = (int)39;
		/// <i>native declaration : c/libtorrent.h:262</i>
		public static final int at_url_seed_alert = (int)40;
		/// <i>native declaration : c/libtorrent.h:263</i>
		public static final int at_file_error_alert = (int)41;
		/// <i>native declaration : c/libtorrent.h:264</i>
		public static final int at_metadata_failed_alert = (int)42;
		/// <i>native declaration : c/libtorrent.h:265</i>
		public static final int at_metadata_received_alert = (int)43;
		/// <i>native declaration : c/libtorrent.h:266</i>
		public static final int at_udp_error_alert = (int)44;
		/// <i>native declaration : c/libtorrent.h:267</i>
		public static final int at_external_ip_alert = (int)45;
		/// <i>native declaration : c/libtorrent.h:268</i>
		public static final int at_listen_failed_alert = (int)46;
		/// <i>native declaration : c/libtorrent.h:269</i>
		public static final int at_listen_succeeded_alert = (int)47;
		/// <i>native declaration : c/libtorrent.h:270</i>
		public static final int at_portmap_error_alert = (int)48;
		/// <i>native declaration : c/libtorrent.h:271</i>
		public static final int at_portmap_alert = (int)49;
		/// <i>native declaration : c/libtorrent.h:272</i>
		public static final int at_portmap_log_alert = (int)50;
		/// <i>native declaration : c/libtorrent.h:273</i>
		public static final int at_fastresume_rejected_alert = (int)51;
		/// <i>native declaration : c/libtorrent.h:274</i>
		public static final int at_peer_blocked_alert = (int)52;
		/// <i>native declaration : c/libtorrent.h:275</i>
		public static final int at_dht_announce_alert = (int)53;
		/// <i>native declaration : c/libtorrent.h:276</i>
		public static final int at_dht_get_peers_alert = (int)54;
		/// <i>native declaration : c/libtorrent.h:277</i>
		public static final int at_stats_alert = (int)55;
		/// <i>native declaration : c/libtorrent.h:278</i>
		public static final int at_cache_flushed_alert = (int)56;
		/// <i>native declaration : c/libtorrent.h:279</i>
		public static final int at_alert = (int)57;
	};
	/**
	 * <i>native declaration : c/libtorrent.h:524</i><br>
	 * enum values
	 */
	/**
	 * <i>native declaration : c/libtorrent.h:524</i><br>
	 * enum values
	 */
	public static interface stats_channel {
		/// <i>native declaration : c/libtorrent.h:513</i>
		public static final int upload_payload = (int)0;
		/// <i>native declaration : c/libtorrent.h:514</i>
		public static final int upload_protocol = (int)1;
		/// <i>native declaration : c/libtorrent.h:515</i>
		public static final int upload_ip_protocol = (int)2;
		/// <i>native declaration : c/libtorrent.h:516</i>
		public static final int upload_dht_protocol = (int)3;
		/// <i>native declaration : c/libtorrent.h:517</i>
		public static final int upload_tracker_protocol = (int)4;
		/// <i>native declaration : c/libtorrent.h:518</i>
		public static final int download_payload = (int)5;
		/// <i>native declaration : c/libtorrent.h:519</i>
		public static final int download_protocol = (int)6;
		/// <i>native declaration : c/libtorrent.h:520</i>
		public static final int download_ip_protocol = (int)7;
		/// <i>native declaration : c/libtorrent.h:521</i>
		public static final int download_dht_protocol = (int)8;
		/// <i>native declaration : c/libtorrent.h:522</i>
		public static final int download_tracker_protocol = (int)9;
		/// <i>native declaration : c/libtorrent.h:523</i>
		public static final int stats_channel_max = (int)10;
	};
	/**
	 * <i>native declaration : c/libtorrent.h:605</i><br>
	 * enum values
	 */
	/**
	 * <i>native declaration : c/libtorrent.h:605</i><br>
	 * enum values
	 */
	public static interface session_remove_options {
		/// <i>native declaration : c/libtorrent.h:603</i>
		public static final int none = (int)0;
		/// <i>native declaration : c/libtorrent.h:604</i>
		public static final int delete_files = (int)1;
	};
	/**
	 * use SES_* tags in tag list<br>
	 * Original signature : <code>void* session_create(int, null)</code><br>
	 * <i>native declaration : c/libtorrent.h:592</i>
	 */
	Pointer session_create(int first_tag, Object... varargs);
	/**
	 * Original signature : <code>void session_close(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:594</i>
	 */
	void session_close(Pointer ses);
	/**
	 * use TOR_* tags in tag list<br>
	 * Original signature : <code>void* session_add_torrent(void*, int, null)</code><br>
	 * <i>native declaration : c/libtorrent.h:599</i>
	 */
	Pointer session_add_torrent(Pointer ses, int first_tag, Object... varargs);
	/**
	 * Original signature : <code>void* session_add_torrent_data(void*, void*, int, const char*)</code><br>
	 * <i>native declaration : c/libtorrent.h:601</i><br>
	 * @deprecated use the safer methods {@link #session_add_torrent_data(com.sun.jna.Pointer, com.sun.jna.Pointer, int, java.lang.String)} and {@link #session_add_torrent_data(com.sun.jna.Pointer, com.sun.jna.Pointer, int, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Pointer session_add_torrent_data(Pointer ses, Pointer resume, int resume_size, Pointer target);
	/**
	 * Original signature : <code>void* session_add_torrent_data(void*, void*, int, const char*)</code><br>
	 * <i>native declaration : c/libtorrent.h:601</i>
	 */
	Pointer session_add_torrent_data(Pointer ses, Pointer resume, int resume_size, String target);
	/**
	 * Original signature : <code>void session_remove_torrent(void*, void*, int)</code><br>
	 * <i>native declaration : c/libtorrent.h:607</i>
	 */
	void session_remove_torrent(Pointer ses, Pointer tor, int options);
	/**
	 * Original signature : <code>int session_get_status(void*, session_status*, int)</code><br>
	 * <i>native declaration : c/libtorrent.h:609</i>
	 */
	int session_get_status(Pointer ses, session_status s, int struct_size);
	/**
	 * use SET_* tags in tag list<br>
	 * Original signature : <code>int session_set_settings(void*, int, null)</code><br>
	 * <i>native declaration : c/libtorrent.h:614</i>
	 */
	int session_set_settings(Pointer ses, int first_tag, Object... varargs);
	/**
	 * Original signature : <code>int session_get_setting(void*, int, void*, int*)</code><br>
	 * <i>native declaration : c/libtorrent.h:616</i><br>
	 * @deprecated use the safer methods {@link #session_get_setting(com.sun.jna.Pointer, int, com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #session_get_setting(com.sun.jna.Pointer, int, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	int session_get_setting(Pointer ses, int tag, Pointer value, IntByReference value_size);
	/**
	 * Original signature : <code>int session_get_setting(void*, int, void*, int*)</code><br>
	 * <i>native declaration : c/libtorrent.h:616</i>
	 */
	int session_get_setting(Pointer ses, int tag, Pointer value, IntBuffer value_size);
	/**
	 * call session_wait_alert or session_pop_alert, and then cast_to_ or session_free_alert<br>
	 * Original signature : <code>void* session_wait_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:621</i>
	 */
	Pointer session_wait_alert(Pointer ses);
	/**
	 * Original signature : <code>void* session_pop_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:623</i>
	 */
	Pointer session_pop_alert(Pointer ses);
	/**
	 * Original signature : <code>void session_free_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:625</i>
	 */
	void session_free_alert(Pointer pop);
	/**
	 * Original signature : <code>int torrent_get_status(void*, torrent_status*, int)</code><br>
	 * <i>native declaration : c/libtorrent.h:627</i>
	 */
	int torrent_get_status(Pointer tor, torrent_status s, int struct_size);
	/**
	 * Original signature : <code>long torrent_get_hash(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:629</i>
	 */
	NativeLong torrent_get_hash(Pointer tor);
	/**
	 * use SET_* tags in tag list<br>
	 * Original signature : <code>int torrent_set_settings(void*, int, null)</code><br>
	 * <i>native declaration : c/libtorrent.h:634</i>
	 */
	int torrent_set_settings(Pointer tor, int first_tag, Object... varargs);
	/**
	 * Original signature : <code>int torrent_get_setting(void*, int, void*, int*)</code><br>
	 * <i>native declaration : c/libtorrent.h:636</i><br>
	 * @deprecated use the safer methods {@link #torrent_get_setting(com.sun.jna.Pointer, int, com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #torrent_get_setting(com.sun.jna.Pointer, int, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	int torrent_get_setting(Pointer tor, int tag, Pointer value, IntByReference value_size);
	/**
	 * Original signature : <code>int torrent_get_setting(void*, int, void*, int*)</code><br>
	 * <i>native declaration : c/libtorrent.h:636</i>
	 */
	int torrent_get_setting(Pointer tor, int tag, Pointer value, IntBuffer value_size);
	/**
	 * Original signature : <code>int torrent_save_state(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:638</i>
	 */
	int torrent_save_state(Pointer tor);
	/**
	 * Original signature : <code>int torrent_pause(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:640</i>
	 */
	int torrent_pause(Pointer tor);
	/**
	 * Original signature : <code>int torrent_resume(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:642</i>
	 */
	int torrent_resume(Pointer tor);
	/**
	 * Original signature : <code>int torrent_recheck(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:644</i>
	 */
	int torrent_recheck(Pointer tor);
	/**
	 * Original signature : <code>bool torrent_has_metadata(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:646</i>
	 */
	byte torrent_has_metadata(Pointer tor);
	/**
	 * Original signature : <code>void* torrent_get_metadata(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:648</i>
	 */
	Pointer torrent_get_metadata(Pointer tor);
	/**
	 * Original signature : <code>int torrent_get_metadata_size(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:650</i>
	 */
	int torrent_get_metadata_size(Pointer tor);
	/**
	 * get torrent title<br>
	 * Original signature : <code>int torrent_info(void*, torrent_title*)</code><br>
	 * <i>native declaration : c/libtorrent.h:655</i>
	 */
	int torrent_info(Pointer tor, torrent_title t);
	/**
	 * free torrent title<br>
	 * Original signature : <code>int torrent_info_free(void*, torrent_title*)</code><br>
	 * <i>native declaration : c/libtorrent.h:660</i>
	 */
	int torrent_info_free(Pointer tor, torrent_title t);
	/**
	 * get files count<br>
	 * Original signature : <code>int torrent_files_count(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:665</i>
	 */
	int torrent_files_count(Pointer tor);
	/**
	 * get file_entry struct<br>
	 * Original signature : <code>int torrent_files_get(void*, int, file_entry*)</code><br>
	 * <i>native declaration : c/libtorrent.h:670</i>
	 */
	int torrent_files_get(Pointer tor, int i, file_entry f);
	/**
	 * free file_entry struct<br>
	 * Original signature : <code>int torrent_files_free(void*, file_entry*)</code><br>
	 * <i>native declaration : c/libtorrent.h:675</i>
	 */
	int torrent_files_free(Pointer tor, file_entry f);
	/**
	 * rename<br>
	 * Original signature : <code>int torrent_files_rename(void*, int, const char*)</code><br>
	 * <i>native declaration : c/libtorrent.h:680</i><br>
	 * @deprecated use the safer methods {@link #torrent_files_rename(com.sun.jna.Pointer, int, java.lang.String)} and {@link #torrent_files_rename(com.sun.jna.Pointer, int, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int torrent_files_rename(Pointer tor, int i, Pointer f);
	/**
	 * rename<br>
	 * Original signature : <code>int torrent_files_rename(void*, int, const char*)</code><br>
	 * <i>native declaration : c/libtorrent.h:680</i>
	 */
	int torrent_files_rename(Pointer tor, int i, String f);
	/**
	 * Original signature : <code>int alert_get_type(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:682</i>
	 */
	int alert_get_type(Pointer alert);
	/**
	 * Original signature : <code>peer_alert* cast_to_peer_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:684</i>
	 */
	peer_alert cast_to_peer_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_peer_alert(peer_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:686</i>
	 */
	void free_peer_alert(peer_alert aa);
	/**
	 * Original signature : <code>read_piece_alert* cast_to_read_piece_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:688</i>
	 */
	read_piece_alert cast_to_read_piece_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_read_piece_alert(read_piece_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:690</i>
	 */
	void free_read_piece_alert(read_piece_alert aa);
	/**
	 * Original signature : <code>file_completed_alert* cast_to_file_completed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:692</i>
	 */
	file_completed_alert cast_to_file_completed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_file_completed_alert(file_completed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:694</i>
	 */
	void free_file_completed_alert(file_completed_alert aa);
	/**
	 * Original signature : <code>file_renamed_alert* cast_to_file_renamed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:696</i>
	 */
	file_renamed_alert cast_to_file_renamed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_file_renamed_alert(file_renamed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:698</i>
	 */
	void free_file_renamed_alert(file_renamed_alert aa);
	/**
	 * Original signature : <code>file_rename_failed_alert* cast_to_file_rename_failed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:700</i>
	 */
	file_rename_failed_alert cast_to_file_rename_failed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_file_rename_failed_alert(file_rename_failed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:702</i>
	 */
	void free_file_rename_failed_alert(file_rename_failed_alert aa);
	/**
	 * Original signature : <code>performance_alert* cast_to_performance_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:704</i>
	 */
	performance_alert cast_to_performance_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_performance_alert(performance_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:706</i>
	 */
	void free_performance_alert(performance_alert aa);
	/**
	 * Original signature : <code>state_changed_alert* cast_to_state_changed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:708</i>
	 */
	state_changed_alert cast_to_state_changed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_state_changed_alert(state_changed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:710</i>
	 */
	void free_state_changed_alert(state_changed_alert aa);
	/**
	 * Original signature : <code>tracker_error_alert* cast_to_tracker_error_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:712</i>
	 */
	tracker_error_alert cast_to_tracker_error_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_tracker_error_alert(tracker_error_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:714</i>
	 */
	void free_tracker_error_alert(tracker_error_alert aa);
	/**
	 * Original signature : <code>tracker_warning_alert* cast_to_tracker_warning_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:716</i>
	 */
	tracker_warning_alert cast_to_tracker_warning_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_tracker_warning_alert(tracker_warning_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:718</i>
	 */
	void free_tracker_warning_alert(tracker_warning_alert aa);
	/**
	 * Original signature : <code>scrape_reply_alert* cast_to_scrape_reply_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:720</i>
	 */
	scrape_reply_alert cast_to_scrape_reply_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_scrape_reply_alert(scrape_reply_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:722</i>
	 */
	void free_scrape_reply_alert(scrape_reply_alert aa);
	/**
	 * Original signature : <code>scrape_failed_alert* cast_to_scrape_failed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:724</i>
	 */
	scrape_failed_alert cast_to_scrape_failed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_scrape_failed_alert(scrape_failed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:726</i>
	 */
	void free_scrape_failed_alert(scrape_failed_alert aa);
	/**
	 * Original signature : <code>tracker_reply_alert* cast_to_tracker_reply_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:728</i>
	 */
	tracker_reply_alert cast_to_tracker_reply_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_tracker_reply_alert(tracker_reply_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:730</i>
	 */
	void free_tracker_reply_alert(tracker_reply_alert aa);
	/**
	 * Original signature : <code>dht_reply_alert* cast_to_dht_reply_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:732</i>
	 */
	dht_reply_alert cast_to_dht_reply_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_dht_reply_alert(dht_reply_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:734</i>
	 */
	void free_dht_reply_alert(dht_reply_alert aa);
	/**
	 * Original signature : <code>tracker_announce_alert* cast_to_tracker_announce_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:736</i>
	 */
	tracker_announce_alert cast_to_tracker_announce_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_tracker_announce_alert(tracker_announce_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:738</i>
	 */
	void free_tracker_announce_alert(tracker_announce_alert aa);
	/**
	 * Original signature : <code>hash_failed_alert* cast_to_hash_failed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:740</i>
	 */
	hash_failed_alert cast_to_hash_failed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_hash_failed_alert(hash_failed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:742</i>
	 */
	void free_hash_failed_alert(hash_failed_alert aa);
	/**
	 * Original signature : <code>peer_ban_alert* cast_to_peer_ban_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:744</i>
	 */
	peer_ban_alert cast_to_peer_ban_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_peer_ban_alert(peer_ban_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:746</i>
	 */
	void free_peer_ban_alert(peer_ban_alert aa);
	/**
	 * Original signature : <code>peer_unsnubbed_alert* cast_to_peer_unsnubbed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:748</i>
	 */
	peer_unsnubbed_alert cast_to_peer_unsnubbed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_peer_unsnubbed_alert(peer_unsnubbed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:750</i>
	 */
	void free_peer_unsnubbed_alert(peer_unsnubbed_alert aa);
	/**
	 * Original signature : <code>peer_snubbed_alert* cast_to_peer_snubbed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:752</i>
	 */
	peer_snubbed_alert cast_to_peer_snubbed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_peer_snubbed_alert(peer_snubbed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:754</i>
	 */
	void free_peer_snubbed_alert(peer_snubbed_alert aa);
	/**
	 * Original signature : <code>peer_error_alert* cast_to_peer_error_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:756</i>
	 */
	peer_error_alert cast_to_peer_error_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_peer_error_alert(peer_error_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:758</i>
	 */
	void free_peer_error_alert(peer_error_alert aa);
	/**
	 * Original signature : <code>peer_connect_alert* cast_to_peer_connect_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:760</i>
	 */
	peer_connect_alert cast_to_peer_connect_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_peer_connect_alert(peer_connect_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:762</i>
	 */
	void free_peer_connect_alert(peer_connect_alert aa);
	/**
	 * Original signature : <code>peer_disconnected_alert* cast_to_peer_disconnected_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:764</i>
	 */
	peer_disconnected_alert cast_to_peer_disconnected_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_peer_disconnected_alert(peer_disconnected_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:766</i>
	 */
	void free_peer_disconnected_alert(peer_disconnected_alert aa);
	/**
	 * Original signature : <code>invalid_request_alert* cast_to_invalid_request_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:768</i>
	 */
	invalid_request_alert cast_to_invalid_request_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_invalid_request_alert(invalid_request_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:770</i>
	 */
	void free_invalid_request_alert(invalid_request_alert aa);
	/**
	 * Original signature : <code>torrent_finished_alert* cast_to_torrent_finished_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:772</i>
	 */
	torrent_finished_alert cast_to_torrent_finished_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_torrent_finished_alert(torrent_finished_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:774</i>
	 */
	void free_torrent_finished_alert(torrent_finished_alert aa);
	/**
	 * Original signature : <code>piece_finished_alert* cast_to_piece_finished_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:776</i>
	 */
	piece_finished_alert cast_to_piece_finished_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_piece_finished_alert(piece_finished_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:778</i>
	 */
	void free_piece_finished_alert(piece_finished_alert aa);
	/**
	 * Original signature : <code>request_dropped_alert* cast_to_request_dropped_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:780</i>
	 */
	request_dropped_alert cast_to_request_dropped_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_request_dropped_alert(request_dropped_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:782</i>
	 */
	void free_request_dropped_alert(request_dropped_alert aa);
	/**
	 * Original signature : <code>block_timeout_alert* cast_to_block_timeout_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:784</i>
	 */
	block_timeout_alert cast_to_block_timeout_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_block_timeout_alert(block_timeout_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:786</i>
	 */
	void free_block_timeout_alert(block_timeout_alert aa);
	/**
	 * Original signature : <code>block_finished_alert* cast_to_block_finished_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:788</i>
	 */
	block_finished_alert cast_to_block_finished_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_block_finished_alert(block_finished_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:790</i>
	 */
	void free_block_finished_alert(block_finished_alert aa);
	/**
	 * Original signature : <code>block_downloading_alert* cast_to_block_downloading_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:792</i>
	 */
	block_downloading_alert cast_to_block_downloading_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_block_downloading_alert(block_downloading_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:794</i>
	 */
	void free_block_downloading_alert(block_downloading_alert aa);
	/**
	 * Original signature : <code>unwanted_block_alert* cast_to_unwanted_block_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:796</i>
	 */
	unwanted_block_alert cast_to_unwanted_block_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_unwanted_block_alert(unwanted_block_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:798</i>
	 */
	void free_unwanted_block_alert(unwanted_block_alert aa);
	/**
	 * Original signature : <code>storage_moved_alert* cast_to_storage_moved_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:800</i>
	 */
	storage_moved_alert cast_to_storage_moved_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_storage_moved_alert(storage_moved_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:802</i>
	 */
	void free_storage_moved_alert(storage_moved_alert aa);
	/**
	 * Original signature : <code>storage_moved_failed_alert* cast_to_storage_moved_failed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:804</i>
	 */
	storage_moved_failed_alert cast_to_storage_moved_failed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_storage_moved_failed_alert(storage_moved_failed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:806</i>
	 */
	void free_storage_moved_failed_alert(storage_moved_failed_alert aa);
	/**
	 * Original signature : <code>torrent_deleted_alert* cast_to_torrent_deleted_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:808</i>
	 */
	torrent_deleted_alert cast_to_torrent_deleted_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_torrent_deleted_alert(torrent_deleted_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:810</i>
	 */
	void free_torrent_deleted_alert(torrent_deleted_alert aa);
	/**
	 * Original signature : <code>torrent_delete_failed_alert* cast_to_torrent_delete_failed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:812</i>
	 */
	torrent_delete_failed_alert cast_to_torrent_delete_failed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_torrent_delete_failed_alert(torrent_delete_failed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:814</i>
	 */
	void free_torrent_delete_failed_alert(torrent_delete_failed_alert aa);
	/**
	 * Original signature : <code>save_resume_data_alert* cast_to_save_resume_data_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:816</i>
	 */
	save_resume_data_alert cast_to_save_resume_data_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_save_resume_data_alert(save_resume_data_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:818</i>
	 */
	void free_save_resume_data_alert(save_resume_data_alert aa);
	/**
	 * Original signature : <code>save_resume_data_failed_alert* cast_to_save_resume_data_failed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:820</i>
	 */
	save_resume_data_failed_alert cast_to_save_resume_data_failed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_save_resume_data_failed_alert(save_resume_data_failed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:822</i>
	 */
	void free_save_resume_data_failed_alert(save_resume_data_failed_alert aa);
	/**
	 * Original signature : <code>torrent_paused_alert* cast_to_torrent_paused_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:824</i>
	 */
	torrent_paused_alert cast_to_torrent_paused_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_torrent_paused_alert(torrent_paused_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:826</i>
	 */
	void free_torrent_paused_alert(torrent_paused_alert aa);
	/**
	 * Original signature : <code>torrent_resumed_alert* cast_to_torrent_resumed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:828</i>
	 */
	torrent_resumed_alert cast_to_torrent_resumed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_torrent_resumed_alert(torrent_resumed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:830</i>
	 */
	void free_torrent_resumed_alert(torrent_resumed_alert aa);
	/**
	 * Original signature : <code>torrent_checked_alert* cast_to_torrent_checked_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:832</i>
	 */
	torrent_checked_alert cast_to_torrent_checked_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_torrent_checked_alert(torrent_checked_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:834</i>
	 */
	void free_torrent_checked_alert(torrent_checked_alert aa);
	/**
	 * Original signature : <code>url_seed_alert* cast_to_url_seed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:836</i>
	 */
	url_seed_alert cast_to_url_seed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_url_seed_alert(url_seed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:838</i>
	 */
	void free_url_seed_alert(url_seed_alert aa);
	/**
	 * Original signature : <code>file_error_alert* cast_to_file_error_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:840</i>
	 */
	file_error_alert cast_to_file_error_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_file_error_alert(file_error_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:842</i>
	 */
	void free_file_error_alert(file_error_alert aa);
	/**
	 * Original signature : <code>metadata_failed_alert* cast_to_metadata_failed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:844</i>
	 */
	metadata_failed_alert cast_to_metadata_failed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_metadata_failed_alert(metadata_failed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:846</i>
	 */
	void free_metadata_failed_alert(metadata_failed_alert aa);
	/**
	 * Original signature : <code>metadata_received_alert* cast_to_metadata_received_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:848</i>
	 */
	metadata_received_alert cast_to_metadata_received_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_metadata_received_alert(metadata_received_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:850</i>
	 */
	void free_metadata_received_alert(metadata_received_alert aa);
	/**
	 * Original signature : <code>udp_error_alert* cast_to_udp_error_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:852</i>
	 */
	udp_error_alert cast_to_udp_error_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_udp_error_alert(udp_error_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:854</i>
	 */
	void free_udp_error_alert(udp_error_alert aa);
	/**
	 * Original signature : <code>external_ip_alert* cast_to_external_ip_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:856</i>
	 */
	external_ip_alert cast_to_external_ip_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_external_ip_alert(external_ip_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:858</i>
	 */
	void free_external_ip_alert(external_ip_alert aa);
	/**
	 * Original signature : <code>listen_failed_alert* cast_to_listen_failed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:860</i>
	 */
	listen_failed_alert cast_to_listen_failed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_listen_failed_alert(listen_failed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:862</i>
	 */
	void free_listen_failed_alert(listen_failed_alert aa);
	/**
	 * Original signature : <code>listen_succeeded_alert* cast_to_listen_succeeded_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:864</i>
	 */
	listen_succeeded_alert cast_to_listen_succeeded_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_listen_succeeded_alert(listen_succeeded_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:866</i>
	 */
	void free_listen_succeeded_alert(listen_succeeded_alert aa);
	/**
	 * Original signature : <code>portmap_error_alert* cast_to_portmap_error_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:868</i>
	 */
	portmap_error_alert cast_to_portmap_error_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_portmap_error_alert(portmap_error_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:870</i>
	 */
	void free_portmap_error_alert(portmap_error_alert aa);
	/**
	 * Original signature : <code>portmap_alert* cast_to_portmap_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:872</i>
	 */
	portmap_alert cast_to_portmap_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_portmap_alert(portmap_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:874</i>
	 */
	void free_portmap_alert(portmap_alert aa);
	/**
	 * Original signature : <code>portmap_log_alert* cast_to_portmap_log_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:876</i>
	 */
	portmap_log_alert cast_to_portmap_log_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_portmap_log_alert(portmap_log_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:878</i>
	 */
	void free_portmap_log_alert(portmap_log_alert aa);
	/**
	 * Original signature : <code>fastresume_rejected_alert* cast_to_fastresume_rejected_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:880</i>
	 */
	fastresume_rejected_alert cast_to_fastresume_rejected_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_fastresume_rejected_alert(fastresume_rejected_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:882</i>
	 */
	void free_fastresume_rejected_alert(fastresume_rejected_alert aa);
	/**
	 * Original signature : <code>peer_blocked_alert* cast_to_peer_blocked_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:884</i>
	 */
	peer_blocked_alert cast_to_peer_blocked_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_peer_blocked_alert(peer_blocked_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:886</i>
	 */
	void free_peer_blocked_alert(peer_blocked_alert aa);
	/**
	 * Original signature : <code>dht_announce_alert* cast_to_dht_announce_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:888</i>
	 */
	dht_announce_alert cast_to_dht_announce_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_dht_announce_alert(dht_announce_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:890</i>
	 */
	void free_dht_announce_alert(dht_announce_alert aa);
	/**
	 * Original signature : <code>dht_get_peers_alert* cast_to_dht_get_peers_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:892</i>
	 */
	dht_get_peers_alert cast_to_dht_get_peers_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_dht_get_peers_alert(dht_get_peers_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:894</i>
	 */
	void free_dht_get_peers_alert(dht_get_peers_alert aa);
	/**
	 * Original signature : <code>stats_alert* cast_to_stats_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:896</i>
	 */
	stats_alert cast_to_stats_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_stats_alert(stats_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:898</i>
	 */
	void free_stats_alert(stats_alert aa);
	/**
	 * Original signature : <code>cache_flushed_alert* cast_to_cache_flushed_alert(void*)</code><br>
	 * <i>native declaration : c/libtorrent.h:900</i>
	 */
	cache_flushed_alert cast_to_cache_flushed_alert(Pointer pop);
	/**
	 * Original signature : <code>void free_cache_flushed_alert(cache_flushed_alert*)</code><br>
	 * <i>native declaration : c/libtorrent.h:902</i>
	 */
	void free_cache_flushed_alert(cache_flushed_alert aa);
}
