package com.github.axet.torrent.rasterbar;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;
/**
 * <i>native declaration : c/libtorrent.h:567</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class udp_error_alert extends Structure {
	/// C type : alert
	public alert alert;
	/// C type : endpoint
	public endpoint entpoint;
	/// C type : error_code
	public error_code errorcode;
	public udp_error_alert() {
		super();
	}
    @Override
    protected List getFieldOrder() {
        return Arrays.asList(new String[]{"alert", "entpoint", "errorcode"});
	}
	/**
	 * @param alert C type : alert<br>
	 * @param entpoint C type : endpoint<br>
	 * @param errorcode C type : error_code
	 */
	public udp_error_alert(alert alert, endpoint entpoint, error_code errorcode) {
		super();
		this.alert = alert;
		this.entpoint = entpoint;
		this.errorcode = errorcode;
	}
	public static class ByReference extends udp_error_alert implements Structure.ByReference {
		
	};
	public static class ByValue extends udp_error_alert implements Structure.ByValue {
		
	};
}
